<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_otp_code</name>
   <tag></tag>
   <elementGuidId>542337ea-4110-4dd3-9c3e-428a09a9f038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;otp_code&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='otp_code']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe8e369c-a2fd-474d-870e-7abc4f66ba99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95642ed7-1cd6-477e-8bae-1723586873d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp_code</value>
      <webElementGuid>408a231d-7282-4601-9247-a3a0c8fbb6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control opt-cls</value>
      <webElementGuid>8e89c5f5-1689-4863-84da-7d1c3a46307a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Verification Code.</value>
      <webElementGuid>7df29db6-ca55-46e7-bccf-f72e5e1427c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;login-body&quot;]/div[@class=&quot;container log-row&quot;]/form[@class=&quot;form-signin m-t-20&quot;]/div[@class=&quot;login-wrap&quot;]/input[@class=&quot;form-control opt-cls&quot;]</value>
      <webElementGuid>5cb00809-41b0-46ad-9cee-5d045cfac04f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='otp_code']</value>
      <webElementGuid>3c574ba2-1099-46be-9302-72d085fe6f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>12b46cd0-f6f6-47a6-83ab-137c38426797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'otp_code' and @placeholder = 'Enter Verification Code.']</value>
      <webElementGuid>3aacb2fa-c453-4abe-860e-c64a5ce767a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
